### ISSUE TITLE
No description

### ISSUE THREAD

**Issue by MichaelWashburnJr** [corbanmailloux/261Toolshare#1]
@corbanmailloux you should totally add a one sentence description to this repo.  I would, but I don't think I have the necessary privileges.  I really just want it so [Github cards](http://lab.lepture.com/github-cards/) looks prettier on my website. See [here](http://mdwjr.com/d/Blog/Post/5/Info/)

**Comment by corbanmailloux** [comment]
Come up with one and I'll add it.

**Comment by MichaelWashburnJr** [comment]
"Toolshare is a system that lets you lend to/borrow from users in your area. Disclaimer: This was built as a project for a class and is not being used as a real system."

**Comment by corbanmailloux** [comment]
Added. I'd like to add the disclaimer to the top of the readme. Then we can close it.
