### ISSUE TITLE
Change Password doesn't work.

### ISSUE THREAD

**Issue by MichaelWashburnJr** [corbanmailloux/261Toolshare#2]
### Steps to Reproduce:
1. Go to your profile
2. Click change password
3. enter old/new password
4. logout
5. try to log in with new password
6. retry with old password.

**Comment by corbanmailloux** [comment]
@mdw7326, please verify that this works for you, as well. Then we can close it.

**Comment by corbanmailloux** [comment]
In case you are curious of the details, it seems that the form was posting to `/password/` when it should have been posting to `/password/change`.

**Comment by corbanmailloux** [comment]
Just tested this in the new public version. All set.
