### ISSUE TITLE
Admin Page's User Table Doesn't Wrap Well

### ISSUE THREAD

**Issue by corbanmailloux** [corbanmailloux/261Toolshare#3]
On the admin page, in the "User" panel, the table will overflow the panel at certain resolutions.
![Example](http://i.imgur.com/vrSC51M.png)

**Comment by corbanmailloux** [comment]
I propose combining the "Active" and "Ban" columns, as they display the same data, and also the "Sharezone Admin" and "Make Sharezone Admin" columns.

Alternatively, we could move the promote and ban actions into an overflow menu or a dropdown, as those actions shouldn't be used all that often.

**Comment by MichaelWashburnJr** [comment]
We can push things into the edit user form too if needed

**Comment by corbanmailloux** [comment]
A temporary or alternate solution is just changing the "Make Sharezone Admin" button text to simply "Promote" and "Demote." 
![Example](http://i.imgur.com/fqY9Jpa.png)

**Comment by corbanmailloux** [comment]
Closing for now. Maybe I'll revisit the formatting on this page some other time, but it _is_ technically solved.
