### ISSUE TITLE
Tool rentals not updated before profile view

### ISSUE THREAD

**Issue by corbanmailloux** [corbanmailloux/261Toolshare#4]
The tool rentals need to be updated before rendering the profile page or the currently rented tools may be incorrect.

Something like:

``` python
# I HATE THE FOLLOWING LINE!
Tool.update_all()
```

would need to be inserted near:
https://github.com/corbanmailloux/261Toolshare/blob/master/project261/toolshare/views.py#L618

**Comment by MichaelWashburnJr** [comment]
classic toolshare comment
