### ISSUE TITLE
No longer hosting this project

### ISSUE THREAD

**Issue by MichaelWashburnJr** [corbanmailloux/261Toolshare#9]
I'm no longer hosting toolshare :( We should remove the link in the repo description

**Comment by corbanmailloux** [comment]
Done. @mdw7326, you know it returns an internal server error if you go to http://ts.mdwjr.com?

**Comment by MichaelWashburnJr** [comment]
@corbanmailloux I have to clean up some nginx config stuff still, but soon it'll 404
